name: Submit the package

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just, sd
      - run: just package
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.7z

  upload:
    needs: package
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: typst/packages
      - uses: actions/download-artifact@v4
        with:
          name: package
      - name: Prepare files
        id: prepare
        run: |
          7z x package.7z -opackage
          rm package.7z

          NAME=$(yq .package.name package/typst.toml)
          VERSION=$(yq .package.version package/typst.toml)
          echo "TITLE=${NAME}:${VERSION}" >> "$GITHUB_OUTPUT"

          mkdir -p packages/preview/${NAME}
          mv package packages/preview/${NAME}/${VERSION}
      - uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}
          commit-message: ${{ steps.prepare.outputs.TITLE }}
          title: ${{ steps.prepare.outputs.TITLE }}
      - name: Summary
        run: |
          echo "Created [PR #${{ steps.pr.outputs.pull-request-number }}](${{ steps.pr.outputs.pull-request-url }})." >> "$GITHUB_STEP_SUMMARY"
