name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: typst-community/setup-typst@v5
        with:
          typst-version: v0.15.0

      - run: just install
      - run: just test
